### PR TITLE
Fix errors when creating table from other process

### PR DESCRIPTION
**Pull request by vexelenn**
This little change should fix errors that occur when using the fixture on multiple processes

### CODE REVIEW

**Comment by mmaslowskicc** [comment]
What's your use case? Why would multiple processes attempt to create the database on the same server started by a fixture?

**Comment by fizyk** [comment]
It rather indicates some tests problems, rather than a bug? You want the test fixture to prepare database the way you need it and not other processes to randomly barge in.

**Comment by vexelenn** [comment]
When I execute a `py.test` with `-n4` and `--repeat` options then I have an error that a database can not be created because it already exists.

**Comment by fizyk** [comment]
And when you run without `-n4` everything is okay?
What's a repeat option?

If it was only `-n4` then it's probably a race condition, although again, two workers won't be able to start mysql at the same time on the same port. mysql server wouldn't be able to start. What does the `--repeat` do?

**Comment by vexelenn** [comment]
I haven't got this error without the `-n` option. The `--repeat` option just repeats the selected group of tests - I use it to find  random failures (for example with `faketime '21 Oct 2016 5:00:54 PM' py.test -m ui -k test_name -n4 --repeat 8`) for one test.
The error I have is:
`E       ProgrammingError: (1007, "Can't create database 'tests'; database exists")`

**Comment by fizyk** [comment]
We can't just fix this error like that, because it indicates that somehow two processes tries to create the database, where only one should do it (the postgresql client fixture),

Try to turn on detailed logging either by your processes to see which process actually does this. Otherwise as I said you'll end up with two processes writing and influencing each other without you noticing anything else but random failed tests.

**Pull request closed without merging**
