### PR TITLE
postgresql: match versions such as 9.4beta3

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
@fizyk @pwilczynskiclearcode travis errors are unrelated, can you take a look?

**Comment by fizyk** [comment]
ach... new pymongo version, new API... :)

**Comment by tomislater** [comment]
Yeah, but also please, fix the pylama.

**Comment by domenkozar** [comment]
Can this be merged or should we wait for travis to be fixed?

**Comment by tomislater** [comment]
Fix for pymongo: https://github.com/ClearcodeHQ/pytest-dbfixtures/pull/110

I think, we should wait for it.

**Comment by fizyk** [comment]
@tomislater pylama's errors are new due to the pylama new version and new linters it does include (fix pending as well)

**Comment by fizyk** [comment]
@domenkozar please rebase against master.

Travis unfortunately doesn't pick against freshest master, when You simply trigger rebuild manually.

**Comment by domenkozar** [comment]
@fizyk done

**Comment by fizyk** [comment]
:+1:

**Pull request merged**
